# Generated by Django 2.2.12 on 2021-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashes',
            name='md5',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashes',
            name='plain_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashes',
            name='sha1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
