# Generated by Django 2.2.12 on 2021-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0002_auto_20210307_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text_file', models.FileField(upload_to='uploads')),
                ('updated', models.BooleanField()),
                ('length', models.IntegerField()),
            ],
        ),
    ]
