# Generated by Django 2.2.12 on 2021-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0003_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='length',
        ),
        migrations.AddField(
            model_name='uploads',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploads',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
