# Generated by Django 2.2.12 on 2021-03-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0005_auto_20210308_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='updated',
            new_name='update',
        ),
    ]
