# Generated by Django 2.2.12 on 2021-03-08 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0008_remove_uploads_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
