# Generated by Django 2.2.12 on 2021-03-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0009_uploads_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='update',
        ),
        migrations.AddField(
            model_name='uploads',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
